# Generated by Django 4.2.4 on 2023-08-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('min_amount', models.IntegerField()),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('applicable_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
