# Generated by Django 4.2.4 on 2023-08-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
    ]
