# Generated by Django 4.2.4 on 2023-08-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_applicable_type_remove_coupon_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_amount',
            new_name='minimum_amount',
        ),
    ]
