# Generated by Django 4.2.3 on 2023-07-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_Image',
            new_name='product_Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
    ]
