# Generated by Django 4.2.3 on 2023-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
