# Generated by Django 4.2.3 on 2023-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_is_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
