# Generated by Django 4.2.3 on 2023-07-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_product_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_phone_verified',
            new_name='is_otp_verified',
        ),
    ]
