# Generated by Django 4.2.3 on 2023-07-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
