# Generated by Django 4.2.3 on 2023-07-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='phone_number'),
        ),
    ]
