# Generated by Django 4.2.3 on 2023-07-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_is_otp_verified_customuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_otp_verified',
        ),
    ]
