# Generated by Django 4.2.3 on 2023-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_is_verified_customuser_is_otp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(upload_to='media/product_images'),
        ),
    ]
