# Generated by Django 4.2.3 on 2023-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
