# Generated by Django 4.2.3 on 2023-07-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_stock_cart_item_quantity_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart_item',
            new_name='CartItem',
        ),
    ]
