# Generated by Django 4.2.3 on 2023-07-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
