# Generated by Django 4.2.3 on 2023-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_stock_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='pin_code',
            field=models.CharField(default=1, max_length=10, verbose_name='pin code'),
            preserve_default=False,
        ),
    ]
