# Generated by Django 4.2.3 on 2023-07-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(max_length=180, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='pin_code',
            field=models.CharField(max_length=10, null=True, verbose_name='pin code'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(max_length=100, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='street'),
        ),
    ]
