# Generated by Django 4.2.3 on 2023-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_user_profile_address_alter_user_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='house_name',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='house_no',
            field=models.CharField(max_length=10, null=True, verbose_name='house number'),
        ),
    ]
