# Generated by Django 4.2.3 on 2023-08-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address',
            field=models.CharField(default='as', max_length=180, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(default='as', max_length=100, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='country',
            field=models.CharField(default='as', max_length=100, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='house_no',
            field=models.CharField(default=1, max_length=10, verbose_name='house number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='as', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=9037848771, verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='pin_code',
            field=models.CharField(default=123456, max_length=10, verbose_name='pin code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(default='as', max_length=100, verbose_name='state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='street',
            field=models.CharField(default='as', max_length=100, verbose_name='street'),
            preserve_default=False,
        ),
    ]
