# Generated by Django 4.2.3 on 2023-08-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_user_profile_address_alter_user_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='phone_number'),
        ),
    ]
