# Generated by Django 4.2.3 on 2023-08-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_user_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_pic',
        ),
    ]
