# Generated by Django 4.2.3 on 2023-08-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_user_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
