# Generated by Django 4.2.3 on 2023-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(max_length=100),
        ),
    ]
