# Generated by Django 4.2.3 on 2023-08-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
