# Generated by Django 4.2.3 on 2023-07-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_strap'),
    ]

    operations = [
        migrations.AddField(
            model_name='strap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
