# Generated by Django 4.2.3 on 2023-07-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_strap_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='strap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.strap'),
            preserve_default=False,
        ),
    ]
