# Generated by Django 4.2.3 on 2023-07-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_date_added_cart_created_at_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strap',
            old_name='product',
            new_name='product_id',
        ),
    ]
