# Generated by Django 4.2.3 on 2023-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_product_strap_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='strap_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
