# Generated by Django 4.2.3 on 2023-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_strap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='strap_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
