# Generated by Django 4.2.3 on 2023-07-31 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_strap_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='strap_type',
        ),
    ]
