# Generated by Django 4.2.3 on 2023-08-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_rename_quantity_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='strap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.strap'),
        ),
    ]
