# Generated by Django 4.2.3 on 2023-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cartitem_strap'),
    ]

    operations = [
        migrations.AddField(
            model_name='strap',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
