# Generated by Django 4.2.3 on 2023-08-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_strap_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strap',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
