# Generated by Django 4.2.3 on 2023-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_rename_quantity_strap_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strap',
            name='strap',
            field=models.CharField(max_length=100),
        ),
    ]
