# Generated by Django 4.2.3 on 2023-08-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_order_checkout_status_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_no',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
    ]
