# Generated by Django 4.2.4 on 2023-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cart_coupon_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
