# Generated by Django 4.2.4 on 2023-08-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
