# Generated by Django 4.2.4 on 2023-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_order_razor_pay_order_id_order_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_signature',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
