# Generated by Django 4.2.4 on 2023-08-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_order_coupon_discount_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
