# Generated by Django 4.2.4 on 2023-08-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_order_coupon_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_charge',
            new_name='shipping_charge',
        ),
    ]
