# Generated by Django 4.2.4 on 2023-08-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_cart_cart_id_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
