# Generated by Django 4.2.4 on 2023-08-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
