# Generated by Django 4.2.4 on 2023-08-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_orderaddress'),
        ('cart', '0037_alter_order_coupon_discount_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.orderaddress'),
        ),
    ]
