# Generated by Django 4.2.3 on 2023-08-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
